Q1. Python program to add two Matrices

In [ ]:
A = [[2,1,4],
     [4,5,6],
     [7,8,9]]

B = [[5,8,1],
     [6,7,3],
     [4,5,9]]


Result =  [[0,0,0],
         [0,0,0],
         [0,0,0]]     

for i in range(len(A)):
  for j in range(len(A[0])):
    Result[i][j] = A[i][j] + B[i][j]     


for r in Result:
  print(r)             

[7, 9, 5]
[10, 12, 9]
[11, 13, 18]


Q2. Python program to multiply two matrices

In [ ]:
A = [[2,1,4],
     [4,5,6],
     [7,8,9]]

B = [[5,8,1],
     [6,7,3],
     [4,5,9]]


Result =  [[0,0,0],
         [0,0,0],
         [0,0,0]] 

for i in range(len(A)):
  for j in range(len(A[0])):
    Result[i][j] = A[i][j] * B[i][j]


for r in Result:
  print(r)            

[10, 8, 4]
[24, 35, 18]
[28, 40, 81]


Q3.Python program for Matrix Product

In [ ]:
A = [[5,7,6],
     [3,9,6],
     [7,4,9]]

B = [[11,8,1],
     [6,10,3],
     [3,5,4]]


Result =  [[0,0,0],
         [0,0,0],
         [0,0,0]] 

for i in range(len(A)):
  for j in range(len(A[0])):
    Result [i][j] =  A[i][j] * B[i][j]


for r in Result:
  print(r)


[55, 56, 6]
[18, 90, 18]
[21, 20, 36]


Q4. Adding and Subtracting Matrices in Python

In [ ]:
#Addition of matrix 

X = [[5,7,6],
     [3,9,6],
     [7,4,9]]

Y = [[11,8,1],
     [6,10,3],
     [3,5,4]]


Result =  [[0,0,0],
         [0,0,0],
         [0,0,0]] 


for i in range(len(X)):
  for j in range(len(X[0])):
    Result [i][j] =  X[i][j] +  Y[i][j]  

for r in Result:
  print(r)          

[16, 15, 7]
[9, 19, 9]
[10, 9, 13]


In [ ]:
#Subtracting matrix

X = [[5,7,6],
     [3,9,6],
     [7,4,9]]

Y = [[11,8,1],
     [6,10,3],
     [3,5,4]]


Result =  [[0,0,0],
         [0,0,0],
         [0,0,0]] 


for i in range(len(X)):
  for j in range(len(X[0])):
    Result [i][j] =  X[i][j] - Y[i][j]  

for r in Result:
  print(r)              

[-6, -1, 5]
[-3, -1, 3]
[4, -1, 5]


Q5. Transpose a matrix in Single line in Python

In [ ]:
import numpy as np


A = [[2,1,4],
     [4,5,6],
     [7,8,9]]




C = np.transpose(A)
print(C)     

[[2 4 7]
 [1 5 8]
 [4 6 9]]


Q6. Python | Matrix creation of n*n

In [ ]:
N = 3

New_matrix = [list(range(1 + N * i, 1 + N * (i + 1))) for i in range(N)]

for m in New_matrix:
    print(m)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


Q7.Python | Get Kth Column of Matrix

In [ ]:
New_matrix = [[1, 2, 3], [8, 9, 7], [4, 5, 6]]

print("The original list is : ",New_matrix)

K = 1

res = [sub[K] for sub in New_matrix]

print("The Kth column of matrix is : " + str(res))

The original list is :  [[1, 2, 3], [8, 9, 7], [4, 5, 6]]
The Kth column of matrix is : [2, 9, 5]


Q8.Python – Vertical Concatenation in Matrix

In [16]:


list_1 = [["Hi", "The"], ["Welcome", "iNeuron"], ["To"]]


print("The original list : " ,list_1)

res = []
N = 0
while N != len(list_1):
	temp = ''
	for idx in list_1:
		
		
		try: temp = temp + idx[N]
		except IndexError: pass
	res.append(temp)
	N = N + 1

res = [ele for ele in res if ele]


print(res)


The original list :  [['Hi', 'The'], ['Welcome', 'iNeuron'], ['To']]
['HiWelcomeTo', 'TheiNeuron']


Q9.Python program to check if a string is palindrome or not

In [ ]:

def isPalindrome(s):
    return s == s[::-1]
s = "dood"

ans = isPalindrome(s)
 
print(ans)

True


Q10. Python program to check whether the string is Symmetrical or Palindrome

In [15]:
def SymPal(string):
    if string==string[::-1]:
        print("The given string is palindrome")
    else:
        print("The given string is not palindrome")

    size=len(string)
    if size%2==0:
       half=size//2
    if string[0:half]==string[half:size]:
        print("The given string is symmentrical")

    else:
        print("The given string is not symmentrical")

SymPal("dood")


The given string is palindrome
The given string is not symmentrical
